- .github/workflows/release.yml
- .npmignore
- .releaserc
- package.json
> feat: add release workflow

- package.json
> fix: update repo url

- src/base-container/index.jsx
- src/common-ui/SocialAuthButtons/index.jsx
- src/common-ui/SocialAuthButtons/index.test.jsx
- src/data/utils.js
- src/forms/enterprise-sso-popup/index.jsx
- src/forms/enterprise-sso-popup/index.test.jsx
- src/forms/login-popup/data/reducers.js
- src/forms/login-popup/index.jsx
- src/forms/login-popup/tests/LoginPopup.test.jsx
- src/forms/registration-popup/components/tests/RegistrationFailureAlert.test.jsx
- src/forms/registration-popup/data/reducers.js
- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
The user should not register automatically in SSO authentication flow if initiated from login form and move to register.
[VAN-1968](https://2u-internal.atlassian.net/browse/VAN-1968)
Locally through unit tests
[screen-capture.webm](https://github.com/edx/frontend-component-authn-edx/assets/78487564/5b4a93b3-afa3-46f4-b1a7-e0315cd683b1)
> feat: Implement SSO auto registration

- package-lock.json
- package.json
> fix: fix release

- src/forms/login-popup/tests/LoginPopup.test.jsx
- src/forms/progressive-profiling-popup/index.test.jsx
- src/forms/registration-popup/components/tests/RegistrationFailureAlert.test.jsx
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- src/forms/reset-password-popup/forgot-password/tests/index.test.jsx
- src/setupTest.js
- src/tracking/trackers/progressive-profiling.js
- src/tracking/trackers/tests/forgot-password.test.jsx
- src/tracking/trackers/tests/progressive-profiling.test.jsx
- src/tracking/trackers/tests/register.test.jsx
- src/tracking/trackers/tests/reset-password.test.jsx
- Add unit tests for segment events for different pages like registration etc
[VAN-1929](https://2u-internal.atlassian.net/browse/VAN-1929)
It has been tested locally.
> feat: add segment events unit tests

- package-lock.json
- package.json
Move frontend-platform package to dependencies.
> fix: fix frontend-platform package

- src/forms/login-popup/components/LoginFailureAlert.jsx
- src/forms/login-popup/index.jsx
- src/forms/registration-popup/components/RegistrationFailureAlert.jsx
- src/forms/registration-popup/index.jsx
- src/forms/reset-password-popup/forgot-password/ForgotPasswordFailureAlert.jsx
- src/forms/reset-password-popup/forgot-password/index.jsx
- src/forms/reset-password-popup/reset-password/index.jsx
Fix the focus issue on the register and login component and add an error focus on the login component page.
https://github.com/edx/frontend-component-authn-edx/assets/7627421/e50d1051-e0a9-4874-89e4-b1419757c491
https://github.com/edx/frontend-component-authn-edx/assets/7627421/add5d7f4-5e6a-488a-9ef4-489c2e95f6e1
> fix: fix focus issue on login and register component

- .env.development
- example/index.jsx
- package-lock.json
- package.json
- src/data/tests/cookies.test.js
- src/data/utils.js
- src/forms/common-components/AuthenticatedRedirection.jsx
- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- Add GTM cookie on registration form success
[VAN-1958](https://2u-internal.atlassian.net/browse/VAN-1958)
- it has been tested locally
- Unit tests are added
> feat: add GTM cookie on registration

- src/base-container/index.jsx
- Make the modal blocking for all forms
- It has been tested locally
> fix: make modal blocking for all forms

- .github/workflows/manual-publish.yml
Change auto publish to manual publish.
> chore: change auto publish to manual publish

- .github/workflows/manual-publish.yml
> fix: manual publish workflow

- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/index.scss
Add the stateful button on the registration form.
https://github.com/edx/frontend-component-authn-edx/assets/7627421/b45b02e2-be59-467c-aba8-589d4682e9c6
> fix: add stateful button in registration form

- src/base-container/index.jsx
- src/forms/fields/auto-suggested-field/index.jsx
- src/forms/progressive-profiling-popup/index.jsx
- src/forms/progressive-profiling-popup/index.test.jsx
- src/forms/progressive-profiling-popup/messages.js
- an error message will appear on the Undetected country option
- an error message will appear on selecting an invalid country
- remove the track query param on the close button click
- can't skip the form if country is not selected.
Through unit tests and manual testing
[screen-capture (1).webm](https://github.com/edx/frontend-component-authn-edx/assets/78487564/ec3e788e-e000-43ff-b83a-194637159172)
> fix: country field error fix

- src/authn-component/index.jsx
- src/common-ui/SocialAuthButtons/index.scss
- src/forms/login-popup/components/AccountActivationMessage.jsx
- src/forms/login-popup/index.jsx
- set the position of the account activation message alert on top of the page.
- set focus on account activation message alert if exists.
- set tpa hind loader height
- Set the SSO provider button background color to white
Through unit tests and manual testing
<table>
<tr>
<td>Activation alert position and focus</td>
<td>
</td>
</tr>
<tr>
<td>Button background color</td>
<td>
</td>
</tr>
<tr>
<td>Loader hight</td>
<td>
</td>
</tr>
</table>
> fix: account activation message

- package-lock.json
- package.json
Reverting https://github.com/edx/frontend-component-authn-edx/commit/d00f6af136f55b4ed284c42df516e6febbe3b618
> fix: revert frontend-platform change in package.json

- src/forms/fields/index.scss
- src/forms/index.scss
- src/index.scss
> fix: fix style files import

- src/base-container/index.jsx
- src/forms/registration-popup/data/reducers.js
- src/forms/registration-popup/data/tests/reducer.test.js
Clear error message on the close button click
[VAN-1984](https://2u-internal.atlassian.net/browse/VAN-1984)
Tested through unit tests and manual testing.
> fix: clear error message

- src/forms/fields/auto-suggested-field/index.jsx
- src/forms/fields/auto-suggested-field/index.scss
- src/forms/fields/index.scss
- Fix left padding issue in dropdown items
I have tested this locally.
> fix: left padding issue in dropdown items

- src/authn-component/data/reducers.js
- src/authn-component/index.jsx
- src/data/segment/utils.js
- src/forms/common-components/AuthenticatedRedirection.jsx
- src/forms/login-popup/index.jsx
- src/forms/progressive-profiling-popup/index.jsx
- src/forms/progressive-profiling-popup/index.test.jsx
- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- src/forms/reset-password-popup/forgot-password/index.jsx
- src/forms/reset-password-popup/reset-password/index.jsx
- src/setupTest.js
- src/tracking/trackers/forgotpassword.js
- src/tracking/trackers/login.js
- src/tracking/trackers/progressive-profiling.js
- src/tracking/trackers/register.js
- src/tracking/trackers/reset-password.js
- src/tracking/trackers/tests/forgot-password.test.jsx
- src/tracking/trackers/tests/login.test.jsx
- src/tracking/trackers/tests/progressive-profiling.test.jsx
- src/tracking/trackers/tests/register.test.jsx
- src/tracking/trackers/tests/reset-password.test.jsx
- Fixed Naming of events
- Added login/register toggle event
- Passed total registration time in registration payload
- Removed register intent property
- Added identify call with the authenticated user on the progressive profiling page
- Added reset password success event
- Added event link tracker for progressive profiling tracked links redirection 
- Fixed register form rendering by default and causing register page event to be fired
- Fixed failing tests
[VAN-1986](https://2u-internal.atlassian.net/browse/VAN-1986)
Locally
> fix: eventing

- src/forms/registration-popup/index.jsx
- Fix scroll issue on register page
It has been tested locally
> fix: fix scroll issue on register page

- src/forms/registration-popup/data/service.js
- Fix multiple refresh token calls issue
Tested locally
> fix: fix multiple refresh token calls issue

- .gitignore
- src/authn-component/tests/index.test.jsx
- src/forms/progressive-profiling-popup/data/reducers.js
- src/forms/progressive-profiling-popup/index.jsx
- src/forms/progressive-profiling-popup/index.scss
- src/forms/progressive-profiling-popup/index.test.jsx
- src/forms/progressive-profiling-popup/messages.js
- src/forms/registration-popup/index.jsx
- fix padding top bottom issue
- subject loading issue fix
- add loading state for the skip button
- update message copy of progressive profiling skip flow
<table>
<tr>
<td>Padding top bottom 64px</td>
<td>
</td>
</tr>
<tr>
<td>Update message copy</td>
<td>
</td>
</tr>
<tr>
<td>Subjects are loading properly & skip button is statefull</td>
<td>
[screen-capture (5).webm](https://github.com/edx/frontend-component-authn-edx/assets/78487564/0337420a-7f6a-46a4-b70b-41fbef3e5268)
</td>
</tr>
</table>
Tested through unit tests and manual testing
> fix: progressive profiling bug fixes

- example/authn-example/index.jsx
- src/forms/login-popup/index.jsx
- src/forms/registration-popup/data/reducers.js
- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- Will auto-register the user only if the user lands on the register page after the SSO flow.
- Pipeline user details will always be filled in when opening the register form if details are available.
- Clear registration backend errors on switching form.
|Before|After|
> fix: fix SSO registration

- src/authn-component/tests/index.test.jsx
- src/forms/progressive-profiling-popup/index.jsx
- src/forms/progressive-profiling-popup/index.test.jsx
Try 1 to fix progressive profiling submit call
[XXX-XXXX](https://2u-internal.atlassian.net/browse/XXX-XXXX)
|Before|After|
> fix: fix progressive profiling submit call

- src/authn-component/tests/index.test.jsx
- src/forms/progressive-profiling-popup/index.jsx
- src/forms/progressive-profiling-popup/index.test.jsx
Reverts edx/frontend-component-authn-edx#95
> Revert "fix: fix progressive profiling submit call"

- src/forms/reset-password-popup/reset-password/index.jsx
Fire reset password page viewed event only when token is valid
[XXX-XXXX](https://2u-internal.atlassian.net/browse/XXX-XXXX)
|Before|After|
> fix: fix reset password page viewed event

- example/authn-example/index.jsx
- src/common-ui/SocialAuthButtons/index.jsx
- src/forms/enterprise-sso-popup/index.jsx
- src/forms/login-popup/index.jsx
- src/forms/progressive-profiling-popup/index.jsx
- src/forms/registration-popup/index.jsx
- src/forms/reset-password-popup/forgot-password/index.jsx
- src/forms/reset-password-popup/reset-password/index.jsx
- src/index.scss
Made the following design elements pill-shaped
- buttons
- stateful buttons
- sso buttons
- input elements
[VAN-1987](https://2u-internal.atlassian.net/browse/VAN-1987)
locally
> feat: make design elements pill shaped

- src/forms/login-popup/index.jsx
- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- src/tracking/trackers/login.js
- Added the app_name in registration request to use as identifier for backend calls
- Added loginSuccess event on successful login
[VAN-2002](https://2u-internal.atlassian.net/browse/VAN-2002)
|Before|After|
> feat: added login success event and an identifier for backend register event

- src/data/utils.js
- src/forms/login-popup/index.jsx
- src/forms/progressive-profiling-popup/index.jsx
- Fix scroll issues on login, register and PP pages
[VAN-1995](https://2u-internal.atlassian.net/browse/VAN-1995)
- it has been tested locally.
|Heading|Video|
| Register|https://github.com/edx/frontend-component-authn-edx/assets/12580995/8bca3ecb-0beb-4699-906b-8ca5bf42d82a|
| PP| https://github.com/edx/frontend-component-authn-edx/assets/12580995/01a6884f-3179-4591-a374-b0eaebaa1bc1|
> fix: fix scroll issues

- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
fixed the key for totalRegistrationTime property
[XXX-XXXX](https://2u-internal.atlassian.net/browse/XXX-XXXX)
|Before|After|
> fix: update totalRegistrationTime property name

- src/data/utils.js
- src/forms/login-popup/index.jsx
- src/forms/registration-popup/index.jsx
- Fix scroll issue on sign-in and sign-up form
[VAN-2000](https://2u-internal.atlassian.net/browse/VAN-2000)
It has been tested locally
|After|
|-----|
|https://github.com/edx/frontend-component-authn-edx/assets/12580995/4d0d5a9b-4e87-437d-a2e9-53c6984543c7 |
> fix: fix scroll issue

- src/common-ui/SocialAuthButtons/index.jsx
- src/forms/fields/marketing-email-opt-out-field/index.jsx
Update cookie value for SSO registration API payload.
> fix: update payload property for SSO registration

- src/authn-component/index.jsx
- src/forms/fields/index.scss
- src/forms/fields/marketing-email-opt-out-field/index.jsx
- src/forms/fields/marketing-email-opt-out-field/index.scss
- src/forms/registration-popup/index.jsx
- src/forms/reset-password-popup/reset-password/index.jsx
- The modal on mobile screen should be full screen. 
- Fix semi colon in reset password loading
- Fix Padding Issues on mobile screen
[VAN-1996](https://2u-internal.atlassian.net/browse/VAN-1996)
[VAN-1998](https://2u-internal.atlassian.net/browse/VAN-1998)
[VAN-1999](https://2u-internal.atlassian.net/browse/VAN-1999)
It has been tested locally
> fix: fix onboarding component issues

- src/forms/login-popup/index.jsx
- src/forms/registration-popup/index.jsx
I have fixed the issue where during a TPA call, if the call is long and I start editing the first form field, when the response comes back, my focus is not taken from the field and moved to the first SSO button.
[VAN-1994](https://2u-internal.atlassian.net/browse/VAN-1994)
Locally Tested
https://github.com/edx/frontend-component-authn-edx/assets/7627421/97aead7d-de53-4cbe-8530-7ef2c1c95b90
https://github.com/edx/frontend-component-authn-edx/assets/7627421/a8ce86e7-5d49-4327-ade9-350eae22c1f2
> fix: fix field focus on TPA delayed Calls

- .env.development
- .env.test
- src/data/constants.js
- src/data/utils.js
- src/forms/fields/marketing-email-opt-out-field/index.jsx
- src/forms/login-popup/index.jsx
- src/forms/login-popup/tests/LoginPopup.test.jsx
- src/forms/registration-popup/components/tests/RegistrationFailureAlert.test.jsx
- src/forms/registration-popup/index.jsx
- src/forms/registration-popup/index.scss
- src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- src/onboarding-component/tests/index.test.jsx
Upon opening of Register and Login modal, URL will be automatically updated.
[XXX-XXXX](https://2u-internal.atlassian.net/browse/XXX-XXXX)
Tested locally
|Before|After|
> feat: update URL of register and login on modal loading

- src/common-ui/SocialAuthButtons/index.jsx
- src/data/cookies.js
- src/data/tests/cookies.test.js
- src/data/tests/utils.test.js
- src/data/utils.js
- src/forms/common-components/AuthenticatedRedirection.jsx
- src/forms/login-popup/index.jsx
- src/forms/progressive-profiling-popup/index.jsx
- src/forms/registration-popup/index.jsx
Using cookies instead of localstorage
|Before|After|
> fix: use cookies instead of localstorage

- src/forms/reset-password-popup/forgot-password/data/reducers.js
- src/forms/reset-password-popup/forgot-password/data/tests/reducer.test.js
- src/forms/reset-password-popup/forgot-password/data/tests/utils.test.js
- src/forms/reset-password-popup/forgot-password/tests/ForgotPasswordFailureAlert.test.jsx
- src/forms/reset-password-popup/forgot-password/tests/index.test.jsx
- src/forms/reset-password-popup/reset-password/components/ResetPasswordSuccess.jsx
- src/forms/reset-password-popup/reset-password/data/reducers.js
- src/forms/reset-password-popup/reset-password/data/sagas.js
- src/forms/reset-password-popup/reset-password/data/tests/reducer.test.js
- src/forms/reset-password-popup/reset-password/data/tests/sagas.test.js
- src/forms/reset-password-popup/reset-password/data/tests/service.test.js
- src/forms/reset-password-popup/reset-password/messages.js
- src/forms/reset-password-popup/reset-password/tests/ResetPasswordSuccess.test.jsx
- src/forms/reset-password-popup/reset-password/tests/index.test.jsx
I've added unit tests to the forgot password feature to improve coverage. As a result, the coverage has increased. Additionally, I've corrected some variable names due to incorrect spellings.
[VAN-2004](https://2u-internal.atlassian.net/browse/VAN-2004)
|Before|After|
| <img width="702" alt="Screenshot 2024-07-11 at 7 07 04 PM" src="https://github.com/edx/frontend-component-authn-edx/assets/7627421/df830a0e-f1db-4ef2-bd2b-4b5d1a9faf0a">| <img width="696" alt="Screenshot 2024-07-11 at 7 01 31 PM" src="https://github.com/edx/frontend-component-authn-edx/assets/7627 …
> chore: add tests for the missing functionality

- src/base-container/index.jsx
- src/forms/fields/marketing-email-opt-out-field/index.jsx
- src/forms/registration-popup/index.scss
fix console errors and warnings
[VAN-2042](https://2u-internal.atlassian.net/browse/VAN-2042)
Locally
**Before:**
https://github.com/user-attachments/assets/26187984-72ae-49d3-8051-d9bed2607d31
**After:**
https://github.com/user-attachments/assets/8886a79b-5193-413b-aae8-b418f905b421
> fix: console errors and warnings

- src/base-container/index.jsx
- Fixed modal scroll issue on mobile screen
[VAN-2059](https://2u-internal.atlassian.net/browse/VAN-2059)
- Tested locally
|After|
|-----|
|https://github.com/user-attachments/assets/b08c16af-b3c9-4523-9f0d-56f63790d495|
> fix: modal scroll issue on mobile screen
