src/forms/reset-password-popup/forgot-password/index.jsx, src/forms/reset-password-popup/forgot-password/tests/index.test.jsx
fix nudge password message copy on email sent success
Through unit tests and manual testing
[screen-capture (2).webm](https://github.com/edx/frontend-component-authn-edx/assets/78487564/32a35a23-bdfa-4872-92d2-c35521a28de9)
=> fix: fix nudge password message copy on email sent success

src/forms/login-popup/index.jsx, src/tracking/trackers/login.js, src/tracking/trackers/tests/login.test.jsx
- Removed incorrect segment event added to the school and organization link
- This fixed the redirect issue as well
Locally
=> fix: redirects on the login popup

src/base-container/index.jsx, src/base-container/index.scss
Description:
- Progressive profiling form should be full height
- it has been tested locally
|After|
|-----|
|![image](https://github.com/edx/frontend-component-authn-edx/assets/12580995/72c040bb-7442-4186-b13b-9be60529b3ec)|
=> fix: progressive profiling should be full height

src/forms/fields/email-field/index.jsx, src/forms/reset-password-popup/forgot-password/index.jsx, src/forms/reset-password-popup/reset-password/index.jsx
First password field on password reset form was being validated on both blur and form submit.
This PR fixes that by removing validation call from submit click
[VAN-1971](https://2u-internal.atlassian.net/browse/VAN-1971)
Locally
|Before|After|
=> fix: password reset validation call on submit

.env.development, example/index.jsx, package-lock.json, package.json, src/data/tests/utils.test.js, src/data/utils.js, src/forms/progressive-profiling-popup/data/utils.js, src/forms/progressive-profiling-popup/index.jsx, src/forms/progressive-profiling-popup/index.test.jsx, src/forms/registration-popup/index.jsx, src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- There should be no error message on the undetected option in country field by default
- cookie value should be on a variable base
- check the user country on the progressive profiling popup, if not set not allow the user to skip or register
- pass country in register payload on the base of country cookie or MFE context API response 
Through unit tests and manual testing
[Video with country code](https://github.com/edx/frontend-component-authn-edx/assets/78487564/1b02c847-62f7-488e-8760-e01cb2586973)
[Video without country code](https://github.com/edx/frontend-component-authn-edx/assets/78487564/2d189c40-7b43-48bb-ac44-37fe1731f5e3)
=> fix: progressive profiling and registration

.env.development, example/index.jsx, src/forms/reset-password-popup/forgot-password/ForgotPasswordSuccess.jsx, src/forms/reset-password-popup/forgot-password/tests/ForgotPasswordSuccess.test.jsx, src/forms/reset-password-popup/messages.js
- Fixed typo in the reset password success message
- The work is based on feedback provided by Alena
N/A
Updated unit test
|Before (Figma SS)|After|
|<img width="749" alt="Screenshot 2024-06-24 at 4 58 42 PM" src="https://github.com/edx/frontend-component-authn-edx/assets/40633976/6d0417cb-46a0-4cea-b685-be10917f50dd">|<img width="799" alt="Screenshot 2024-06-24 at 4 58 17 PM" src="https://github.com/edx/frontend-component-authn-edx/assets/40633976/3df0d5ab-bf06-48cb-ba29-97afb098ae9b">
=> fix: password reset success message typo

.gitignore, example/index.jsx, src/common-ui/InlineLink/index.jsx, src/forms/login-popup/components/AccountActivationMessage.jsx, src/forms/login-popup/components/LoginFailureAlert.jsx, src/forms/login-popup/components/LoginFailureAlert.test.jsx, src/forms/login-popup/index.scss, src/forms/registration-popup/index.jsx, src/forms/reset-password-popup/forgot-password/index.jsx, src/forms/reset-password-popup/reset-password/components/ResetPasswordFailure.jsx
Fixed following bugs identified during the bugbash
- Clicking on any support email address now opens the email app on the device
- TOS are now hidden when auto registering account
- Reset password link on login failure alert is now working, in page redirecting to reset password page
- Help Center link on forgot password page opens in new tab
- Reduced the gap between error message alert and heading on reset password page
For reference see the [bugbash sheet](https://docs.google.com/spreadsheets/d/1fB1C7L3hhoYs1LlXdjTMeBAUnYCDuMszBacbMbnNUTA/edit?usp=sharing).
Updated tests where needed + tested the functionality locally
|Before|After|
|<img width="685" alt="Screenshot 2024-06-26 at 7 08 46 PM" src="https://github.com/edx/frontend-component-authn-edx/assets/40633976/4c3306e6 …
=> fix: hyperlink related issues

src/forms/fields/password-field/index.jsx, src/forms/fields/password-field/index.test.jsx, src/forms/fields/password-field/messages.jsx, src/forms/registration-popup/tests/RegistrationPopup.test.jsx, src/forms/reset-password-popup/messages.js
This PR will address the following issues:
- Only one tooltip will be displayed at a time. (You can reproduce the error on the master branch by pressing the Shift + Tab button).
- It will eliminate the need to list the fulfilled password requirements under the error message, and ensure that the password field is updated for both the reset password and registration forms.
https://github.com/edx/frontend-component-authn-edx/assets/7627421/d3376093-5f5b-4dcf-b420-c5c84b645fde
https://github.com/edx/frontend-component-authn-edx/assets/7627421/4c7d8061-0111-4604-a967-3dc42a40b850
=> fix: fix the password field behaviour

src/forms/fields/email-field/index.jsx, src/forms/fields/email-field/index.test.jsx, src/forms/reset-password-popup/forgot-password/index.jsx
When the email field is validated on blur in the forgot password form, it shows both an empty field error message and an invalid email message.
[VAN-1991](https://2u-internal.atlassian.net/browse/VAN-1991)
Added Test
https://github.com/edx/frontend-component-authn-edx/assets/7627421/59b26640-fb90-469c-983c-82f95ef9ff08
=> fix: Validate Email field on Blur

src/forms/login-popup/index.jsx, src/forms/registration-popup/index.jsx
In this PR, we fix the issue where the focus goes to the error alert on login and registration failure. Now, the screen reader reads the alert error message.
[VAN-1990](https://2u-internal.atlassian.net/browse/VAN-1990)
Locally
https://github.com/edx/frontend-component-authn-edx/assets/7627421/c524ff9f-6ac9-49c7-b390-8e28912c85d3
=> fix: fix error alert focus on login and registration form

src/forms/login-popup/data/reducers.js, src/forms/login-popup/index.jsx, src/forms/login-popup/tests/LoginPopup.test.jsx, src/forms/registration-popup/data/reducers.js, src/forms/registration-popup/index.jsx, src/forms/registration-popup/tests/RegistrationPopup.test.jsx, src/forms/reset-password-popup/forgot-password/data/reducers.js, src/forms/reset-password-popup/forgot-password/index.jsx, src/forms/reset-password-popup/forgot-password/tests/index.test.jsx, src/onboarding-component/tests/index.test.jsx
- Persistence of login, signup forgot password forms
- Error alert should not be visible on forms switches
[VAN-1957](https://2u-internal.atlassian.net/browse/VAN-1957)
[VAN-2007](https://2u-internal.atlassian.net/browse/VAN-2007)
It has been tested locally
=> feat: persistance of login and singup forms

src/forms/fields/email-field/index.jsx, src/forms/fields/email-field/index.test.jsx, src/forms/fields/name-field/index.jsx, src/forms/fields/name-field/index.test.jsx, src/forms/fields/password-field/index.jsx, src/forms/registration-popup/index.jsx
- Clear Backend error if field is focused and error exists in redux
[VAN-2011](https://2u-internal.atlassian.net/browse/VAN-2011)
- it has been tested locally.
=> fix: backend error clear on focus

src/forms/login-popup/index.jsx, src/forms/login-popup/tests/LoginPopup.test.jsx
This pull request addresses the issue by passing the onboardingComponentContext to the payload, which fixes the enrollment problem:
[VAN-2014](https://2u-internal.atlassian.net/browse/VAN-2014)
Locally tested
https://github.com/user-attachments/assets/d030c67d-35d8-4906-a3ee-52e151f8f4a2
https://github.com/user-attachments/assets/fa4e4fa0-8e63-43fc-aa28-acd28cab7c1c
=> fix: add missing context in login api

src/base-container/index.jsx, src/forms/login-popup/data/reducers.js, src/forms/reset-password-popup/forgot-password/index.jsx, src/forms/reset-password-popup/forgot-password/tests/index.test.jsx, src/onboarding-component/index.jsx
- Hide “Back to login button on forgot password when password nudge case occurs 
- Redirect to finish auth URL when user click on cross button on forgot password form
[VAN-2008](https://2u-internal.atlassian.net/browse/VAN-2008)
- It has been tested locally 
| Before  | After |
| ------------- | ------------- |
| https://github.com/user-attachments/assets/bdd14c97-6fc9-495f-98f5-ec1ea2bca834|https://github.com/user-attachments/assets/3c977ab8-0ce2-407a-9c97-22f080d0a31a|
=> fix: fix login nudge issue

src/forms/progressive-profiling-popup/index.test.jsx, src/forms/progressive-profiling-popup/messages.js
Update the country message when the user clicks the skip button, provided the user has a country value.
[VAN-2009](https://2u-internal.atlassian.net/browse/VAn-2009)
|Before|After|
|   <img width="923" alt="Screenshot 2024-07-19 at 2 36 19 PM" src="https://github.com/user-attachments/assets/9b8f2fe2-563e-4774-a6e9-7124ce2e1888">   |    <img width="935" alt="Screenshot 2024-07-19 at 2 36 53 PM" src="https://github.com/user-attachments/assets/71be2ae3-fddd-4f72-9614-9fe3eac519b6">  |
=> fix: update country msg on skip button

src/forms/progressive-profiling-popup/index.jsx, src/forms/progressive-profiling-popup/index.test.jsx, src/forms/registration-popup/index.jsx, src/forms/registration-popup/tests/RegistrationPopup.test.jsx
User ID was not being passed in the registration success event so this PR makes an identify call before firing the registration success event so that the success event can have the user id.
[VAN-2018](https://2u-internal.atlassian.net/browse/VAN-2018)
|Before|After|
=> fix: user id not passing in registration success event

src/forms/reset-password-popup/reset-password/index.jsx, src/tracking/trackers/login.js, src/tracking/trackers/register.js
- In this PR, I fixed the issue where the page view event was not being fired when the reset password modal was opened.
[VAN-2032](https://2u-internal.atlassian.net/browse/VAN-2032)
|Before|After|
=> fix: fix segment event on reset password modal

src/base-container/index.jsx, src/base-container/index.test.jsx
It was noticed that the page viewed event was fired for both login and register pages when 
- login page was opened after register page or
- register page was opened after login page.
[VAN-2043](https://2u-internal.atlassian.net/browse/VAN-2043)
Locally
|Before|After|
=> fix: both login register page viewed event fires

src/data/constants.js, src/forms/registration-popup/index.jsx, src/forms/reset-password-popup/forgot-password/index.jsx, src/forms/reset-password-popup/forgot-password/tests/index.test.jsx
This PR fixes the issue where, when the user clicks on the Forgot Password link, the URL should change to                            
`?authMode=ResetPassword.`
[VAN-2047](https://2u-internal.atlassian.net/browse/VAN-2047)
Tested through unit tests and updated the tests
https://github.com/user-attachments/assets/4ed2ae48-3a42-4fea-915b-0af9257201cc
=> fix: add query param for forgot password form

src/common-ui/SocialAuthButtons/index.test.jsx, src/data/tests/cookies.test.js, src/data/tests/utils.test.js, src/forms/common-components/tests/AuthenticatedRedirection.test.jsx, src/forms/enterprise-sso-popup/data/utils.test.js, src/forms/enterprise-sso-popup/index.test.jsx, src/forms/login-popup/components/AccountActivationMessage.test.jsx, src/forms/login-popup/data/tests/reducer.test.js, src/forms/registration-popup/data/tests/reducer.test.js, src/forms/registration-popup/data/tests/service.test.js, src/onboarding-component/data/tests/utils.test.js, src/onboarding-component/tests/index.test.jsx
In this PR, I have added tests for the registration reducer and service, and login files which has slightly increased our coverage.
[VAN-2001](https://2u-internal.atlassian.net/browse/VAN-2001)
|Before|After|
|   <img width="962" alt="Screenshot 2024-08-02 at 2 57 52 PM" src="https://github.com/user-attachments/assets/d36d2ac4-3ff7-4e24-a5ca-544d7d878115">   |     <img width="952" alt="Screenshot 2024-08-02 at 2 59 17 PM" src="https://github.com/user-attachments/assets/206b83f6-b669-4aa9-9685-9260e8da9857"> |
=> fix: add unit tests for different modules to improve coverage

src/forms/registration-popup/index.jsx, src/forms/registration-popup/tests/RegistrationPopup.test.jsx
- Convert totalRegistrationTime to snake case
[VAN-1816](https://2u-internal.atlassian.net/browse/VAN-1816)
- Tested locally
Here is the backend PR https://github.com/openedx/edx-platform/pull/35333
=> fix: convert totalRegistrationTime to snake case

.eslintrc.js, babel.config.js, package-lock.json, package.json, webpack.dev.config.js
Part of https://github.com/openedx/axim-engineering/issues/23
- Replaced packages `@edx/frontend-build` to use `openedx` namespace, updated respective imports
- Major version upgrade for `frontend-build` to v14
- `frontend-platform` peerDependency updated
=> feat: replaced @edx/frontend-build to use openedx namespace

.github/workflows/ci.yml
Completed upgrade to Node 20 by removing the Node 18 CI check and using `.nvmrc` for version to use.
See [the tracking issue](https://github.com/edx/frontend-component-authn-edx/issues/135) for further information.
=> chore: Remove support for Node 18
